# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80b8d85e5c36bd1d2a814fb258a747b6c782e4ae25d29277df63fe628268df60fe6ba566f9a3e5bc6285c64264b1936acde1850038e39a506f1b4b62d6b36928

test:
  secret_key_base: 15f29a8ea414564ba08168d9c0bbb393ff16b81128916c80cf22e9d5b44fd72da520300f63cd4a71048d19597cd0cb8ab739b4a1d179b5ccc43ed4cf345af61d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
